---
name: build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install Docker
        run: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.0.4

      - name: Build and push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          context: .
          file: ./Dockerfile
          build-args: VERSION=${{ steps.dotenv.outputs.version }}
          push: true
          tags: |
            ${{ steps.dotenv.outputs.repo }}:latest
            ${{ steps.dotenv.outputs.repo }}:${{ steps.dotenv.outputs.version }}
