---
pipeline:
  build:
    image: docker:23.0.2
    secrets:
      - REGISTRY_USERNAME
      - REGISTRY_PASSWORD
    commands:
      - while ! docker ps -a; do sleep 1; done
      - apk add --no-cache make
      - docker info
      - make login
      - make release
    volumes:
      - "certs:/certs"
      - "sock:/var/run"

services:
  dind:
    image: docker:20.10.23-dind
    privileged: true
    environment:
      DOCKER_DRIVER: "overlay2"
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - "certs:/certs"
      - "sock:/var/run"

when:
  branch:
    include:
      - master
    exclude:
      - renovate/*
  event:
    - push
